Repository AugurProject/augur, pull requests merged in 2019-05, with the labels that each got.

#2030 Make log processors work with OrderEvent
  packages/augur-artifacts/src/addresses.json
  packages/augur-node/src/blockchain/log-processors/index.ts
Labels: Chore

#2031 Make augur node process extraInfo so things work again
  packages/augur-node/src/blockchain/log-processors/market-created.ts
  packages/augur-node/src/blockchain/process-logs.ts
  packages/augur-node/src/blockchain/start-augur-listeners.ts
  packages/augur-node/src/types.ts
Labels: Bug

#2078 Fix up docker addresses
  packages/augur-artifacts/src/addresses.json
  packages/augur-artifacts/src/upload-block-numbers.json
  packages/augur-tools/docker-builder/Dockerfile
  packages/augur-tools/scripts/copy-docker-files.sh
Labels: Bug

#2097 Robert/create market and orders
  azure-pipelines.yml
  package.json
  packages/augur-node/src/blockchain/bulk-sync-augur-node-with-blockchain.ts
  packages/augur-node/src/blockchain/log-processors/order-created.ts
  packages/augur-node/src/blockchain/process-logs.ts
  packages/augur-sdk/src/utils.ts
  packages/augur-test/flash/debug-options.json
  packages/augur-test/flash/index.ts
  packages/augur-test/flash/trade-complete-sets.ts
  packages/augur-test/package.json
  packages/augur-test/src/flash/create-canned-markets-and-orders.ts
  packages/augur-test/src/flash/data/canned-markets.ts
  packages/augur-test/src/flash/index.ts
  packages/augur-test/src/index.ts
  packages/augur-test/src/libs/ContractAPI.ts
  packages/augur-test/src/libs/LocalAugur.ts
  packages/augur-test/src/libs/MakeDbMock.ts
  packages/augur-test/src/libs/Utils.ts
  packages/augur-test/src/libs/index.ts
  packages/augur-test/src/tests/api/Contracts.test.ts
  packages/augur-test/src/tests/api/Trade.test.ts
  packages/augur-test/src/tests/api/robert.test.ts
  packages/augur-test/src/tests/state/DB.test.ts
  packages/augur-test/src/tests/state/HTTPEndpoint.test.ts
  packages/augur-test/src/tests/state/Rollback.test.ts
  packages/augur-test/src/tests/state/SyncableDB.test.ts
  packages/augur-test/src/tests/state/UserSyncableDB.test.ts
  packages/augur-test/src/tests/state/api/Markets.test.ts
  packages/augur-test/src/tests/state/api/Router.test.ts
  packages/augur-test/src/tests/state/api/Trading.test.ts
  packages/augur-test/src/tests/state/api/Users.test.ts
  packages/augur-test/tsconfig.json
  packages/augur-tools/docker-builder/run-geth-and-deploy.sh
  packages/augur-tools/scripts/canned-markets.sh
  packages/augur-tools/scripts/dp/lib/create-markets.js
  packages/augur-tools/scripts/dp/lib/create-order-book.js
  packages/augur-tools/scripts/dp/lib/create-orders.js
  packages/augur-tools/src/dp/data/canned-markets.ts
  packages/augur-tools/src/dp/data/yes-no-order-book.ts
  packages/augur-tools/src/dp/index.ts
  packages/augur-tools/src/dp/lib/create-market.ts
  packages/augur-tools/src/dp/lib/create-markets.ts
  yarn.lock
Labels: Chore

#2202 Pgebheim/experimental connector
  package.json
  packages/augur-sdk/package.json
  packages/augur-sdk/src/connector/connector.ts
  packages/augur-sdk/src/connector/http-connector.test.ts
  packages/augur-sdk/src/connector/http-connector.ts
  packages/augur-sdk/src/connector/seo-connector.ts
  packages/augur-sdk/src/connector/ws-connector.ts
  packages/augur-sdk/src/state/Controller.ts
  packages/augur-sdk/src/state/api/Router.ts
  yarn.lock
Labels: Feature
