Repository AugurProject/augur, pull requests merged in 2020-04, with the labels that each got.

#7207 filter by universe id
  packages/augur-sdk/src/state/getter/Markets.ts
Labels: Bug

#7307 Add isWarpSync flag to ReportingStateChanged payload
  packages/augur-sdk/src/state/db/MarketDB.ts
Labels: type/enhancement

#7356 Improve bulk sync error
  packages/augur-sdk/src/state/sync/BulkSyncStrategy.ts
Labels: type/chore

#7412 My bets
  packages/augur-ui/src/modules/common/buttons.styles.less
  packages/augur-ui/src/modules/common/buttons.tsx
  packages/augur-ui/src/modules/common/constants.ts
  packages/augur-ui/src/modules/common/filter-notice.styles.less
  packages/augur-ui/src/modules/common/filter-notice.tsx
  packages/augur-ui/src/modules/common/icons.tsx
  packages/augur-ui/src/modules/common/selection.styles.less
  packages/augur-ui/src/modules/common/selection.tsx
  packages/augur-ui/src/modules/filter-sort/components/filter-search.tsx
  packages/augur-ui/src/modules/markets-list/components/markets-view.styles.less
  packages/augur-ui/src/modules/markets-list/components/markets-view.tsx
  packages/augur-ui/src/modules/portfolio/components/portfolio-view/my-bets.styles.less
  packages/augur-ui/src/modules/portfolio/components/portfolio-view/my-bets.tsx
  packages/augur-ui/src/modules/portfolio/components/portfolio-view/portfolio-view.tsx
Labels: project/sportsbook

#7410 Pg/add mesh events
  packages/augur-sdk/src/api/ZeroX.ts
  packages/augur-sdk/src/constants.ts
  packages/augur-sdk/src/state/Controller.ts
  packages/augur-sdk/src/state/db/ZeroXOrders.ts
  packages/augur-test/src/libs/MockBrowserMesh.ts
  packages/augur-test/src/libs/MockMeshServer.ts
  packages/augur-ui/src/modules/app/actions/update-app-status.ts
  packages/augur-ui/src/modules/app/reducers/app-status.ts
  packages/augur-ui/src/modules/common/constants.ts
  packages/augur-ui/src/modules/events/actions/listen-to-updates.ts
  packages/augur-ui/src/modules/events/actions/log-handlers.ts
  packages/augur-ui/src/services/browser-mesh.ts
Labels: type/enhancement

#7397 Remove addresses.json + references to it
  debugging.md
  packages/augur-artifacts/src/addresses.json
  packages/augur-tools/scripts/deploy-and-can-all.sh
  packages/augur-tools/scripts/deploy-merge-addresses.py
  packages/augur-tools/src/flash/scripts.ts
Labels: type/chore

#7442 Gh 7317 chaos monkey
  packages/augur-sdk/src/state/create-api.ts
  packages/augur-tools/src/flash/chaos-monkey.ts
  packages/augur-tools/src/flash/flash.ts
  packages/augur-tools/src/flash/order-firehose.ts
  packages/augur-tools/src/flash/orderbook-shaper.ts
  packages/augur-tools/src/flash/perf-setup.ts
  packages/augur-tools/src/flash/performance.ts
  packages/augur-tools/src/flash/scripts.ts
  packages/augur-tools/src/flash/util.ts
  packages/augur-tools/src/libs/contract-api.ts
  packages/augur-ui/src/services/augursdk.ts
Labels: area/testing, release/v2

#7483 Pg/always resync orders on mesh ready
  packages/augur-sdk/src/constants.ts
  packages/augur-sdk/src/state/db/ZeroXOrders.ts
  packages/augur-ui/src/modules/events/actions/listen-to-updates.ts
  packages/augur-ui/src/services/browser-mesh.ts
Labels: status/wip

#7496 App status conversion
  packages/augur-ui/src/main.tsx
  packages/augur-ui/src/modules/app/actions/init-augur.ts
  packages/augur-ui/src/modules/app/actions/update-app-status.ts
  packages/augur-ui/src/modules/app/components/app.tsx
  packages/augur-ui/src/modules/app/components/inner-nav/markets-list-filters.tsx
  packages/augur-ui/src/modules/app/components/inner-nav/markets-list-sortBy.tsx
  packages/augur-ui/src/modules/app/components/side-nav/side-nav.tsx
  packages/augur-ui/src/modules/app/components/top-bar.tsx
  packages/augur-ui/src/modules/app/containers/app.ts
  packages/augur-ui/src/modules/app/containers/category-filters.ts
  packages/augur-ui/src/modules/app/containers/markets-list-filters.ts
  packages/augur-ui/src/modules/app/containers/markets-list-sortBy.ts
  packages/augur-ui/src/modules/app/containers/top-bar.ts
  packages/augur-ui/src/modules/app/reducers/app-status.ts
  packages/augur-ui/src/modules/app/store/app-status-hooks.ts
  packages/augur-ui/src/modules/app/store/constants.ts
  packages/augur-ui/src/modules/auth/actions/login-with-fortmatic.ts
  packages/augur-ui/src/modules/auth/actions/login-with-injected-web3.ts
  packages/augur-ui/src/modules/auth/actions/login-with-portis.ts
  packages/augur-ui/src/modules/auth/actions/login-with-torus.ts
  packages/augur-ui/src/modules/auth/actions/logout.ts
  packages/augur-ui/src/modules/auth/actions/update-sdk.ts
  packages/augur-ui/src/modules/auth/components/connect-dropdown/connect-dropdown.tsx
  packages/augur-ui/src/modules/auth/containers/connect-dropdown.ts
  packages/augur-ui/src/modules/common/form.tsx
  packages/augur-ui/src/modules/create-market/components/create-market-view/create-market-view.tsx
  packages/augur-ui/src/modules/create-market/containers/create-market.ts
  packages/augur-ui/src/modules/create-market/containers/form-details.ts
  packages/augur-ui/src/modules/market-cards/containers/market-card.ts
  packages/augur-ui/src/modules/market-charts/containers/depth.ts
  packages/augur-ui/src/modules/markets-list/components/markets-landing-page.tsx
  packages/augur-ui/src/modules/markets-list/components/markets-list.tsx
  packages/augur-ui/src/modules/markets-list/components/markets-view.tsx
  packages/augur-ui/src/modules/markets-list/containers/markets-landing-page-container.ts
  packages/augur-ui/src/modules/markets-list/containers/markets-view-container.ts
  packages/augur-ui/src/modules/modal/common.tsx
  packages/augur-ui/src/modules/modal/containers/modal-signin.ts
  packages/augur-ui/src/modules/modal/containers/modal-unsigned-orders.ts
  packages/augur-ui/src/modules/modal/signin.tsx
  packages/augur-ui/src/modules/modal/unsigned-orders.tsx
  packages/augur-ui/src/modules/orders/actions/liquidity-management.ts
  packages/augur-ui/src/modules/trading/components/form.tsx
  packages/augur-ui/src/modules/trading/components/trading-form.tsx
  packages/augur-ui/src/modules/trading/components/wrapper.tsx
  packages/augur-ui/src/modules/trading/containers/form.ts
  packages/augur-ui/src/modules/types.ts
Labels: project/sportsbook

#7498 add search filters
  packages/augur-ui/src/modules/common/constants.ts
  packages/augur-ui/src/modules/filter-sort/components/filter-search.tsx
  packages/augur-ui/src/modules/portfolio/components/portfolio-view/my-bets.tsx
  packages/augur-ui/src/modules/portfolio/store/constants.ts
Labels: project/sportsbook

#7502 Betting UI - Convert Categories Section to new style
  packages/augur-ui/src/modules/app/components/inner-nav/category-filters.styles.less
  packages/augur-ui/src/modules/app/components/inner-nav/markets-list-filters.styles.less
  packages/augur-ui/src/modules/common/form.styles.less
Labels: project/sportsbook

#7519 Market view header
  packages/augur-ui/src/assets/styles/_typography.less
  packages/augur-ui/src/modules/common/buttons.styles.less
  packages/augur-ui/src/modules/common/buttons.tsx
  packages/augur-ui/src/modules/common/labels.styles.less
  packages/augur-ui/src/modules/common/labels.tsx
  packages/augur-ui/src/modules/market/components/common/common.styles.less
  packages/augur-ui/src/modules/market/components/common/common.tsx
  packages/augur-ui/src/modules/market/components/market-header/market-header.styles.less
  packages/augur-ui/src/modules/market/components/market-header/market-header.tsx
  packages/augur-ui/src/modules/market/components/market-view/betting-market-view.styles.less
  packages/augur-ui/src/modules/market/components/market-view/betting-market-view.tsx
  packages/augur-ui/src/modules/market/components/market-view/market-view.tsx
  packages/augur-ui/src/modules/routes/components/routes/routes.tsx
  packages/augur-ui/src/modules/routes/constants/components.ts
Labels: project/sportsbook

#7564 Fix service typo
  packages/augur-ui/src/modules/common/constants.ts
Labels: project/trading, type/chore

#7563 Market pg visuals
  packages/augur-ui/src/modules/common/icons.tsx
  packages/augur-ui/src/modules/market/components/common/common.styles.less
  packages/augur-ui/src/modules/market/components/common/common.tsx
  packages/augur-ui/src/modules/market/components/market-view/betting-market-view.styles.less
  packages/augur-ui/src/modules/market/components/market-view/betting-market-view.tsx
  packages/augur-ui/src/modules/reporting/common.styles.less
Labels: project/sportsbook

#7584 Don't syncFTS on handleMergeEvent
  packages/augur-sdk/src/state/db/MarketDB.ts
Labels: area/audit, release/v2, type/optimization
