Repository AugurProject/augur, pull requests merged in 2020-08, with the labels that each got.

#8807 Do not call laod uni every block
  packages/augur-ui/src/modules/events/actions/log-handlers.ts
  packages/augur-ui/src/modules/universe/actions/load-universe-details.ts
Labels: release/v2.1

#8808 Fixes local IPFS hosting.
  packages/augur-ui/src/index.ejs
Labels: status/confirmed, type/bug

#8829 added more invalid explainer
  packages/augur-ui/src/modules/create-market/constants.ts
Labels: type/enhancement

#8845 Point to genesis oi cash
  packages/augur-artifacts/src/environments/mainnet.json
  packages/augur-sdk/src/api/ZeroX.ts
Labels: type/enhancement

#8848 make web3 default
  packages/augur-ui/src/modules/modal/containers/modal-signin.ts
Labels: type/enhancement

#8850 update dropdown buttons
  packages/augur-ui/src/modules/auth/connect-dropdown.styles.less
  packages/augur-ui/src/modules/common/icons.tsx
Labels: project/sportsbook

#8851 Update Best Offers
  packages/augur-sdk/src/api/BestOffer.ts
  packages/augur-ui/src/modules/account/components/account-view.styles.less
  packages/augur-ui/src/modules/app/components/app.styles.less
Labels: project/sportsbook

#8894 Bruno/8873
  packages/augur-ui/src/modules/account/components/open-markets.tsx
  packages/augur-ui/src/modules/account/components/transactions.styles.less
  packages/augur-ui/src/modules/common/buttons.styles.less
  packages/augur-ui/src/modules/common/icons.tsx
  packages/augur-ui/src/modules/common/selection.styles.less
  packages/augur-ui/src/modules/portfolio/components/common/box-header.styles.less
  packages/augur-ui/src/modules/portfolio/components/common/empty-display.styles.less
  packages/augur-ui/src/modules/portfolio/components/common/filter-box.tsx
  packages/augur-ui/src/modules/portfolio/components/favorites/favorites.styles.less
  packages/augur-ui/src/modules/portfolio/components/markets/markets.styles.less
  packages/augur-ui/src/modules/portfolio/components/markets/markets.tsx
Labels: project/sportsbook

#9002 Matic Mumbai Deploy
  packages/augur-artifacts/src/environments/mumbai.json
Labels: type/enhancement
