Repository AugurProject/augur, pull requests merged in 2020-05, with the labels that each got.

#7616 Sports Betting - My Accounts - Notifications
  packages/augur-ui/src/assets/styles/_typography.less
  packages/augur-ui/src/modules/account/components/account-view.styles.less
  packages/augur-ui/src/modules/account/components/notification.styles.less
Labels: project/sportsbook

#7623 Pg/zerox debugging
  packages/augur-artifacts/src/environments/kovan.json
  packages/augur-logger/src/StandardLogger.ts
  packages/augur-logger/src/index.ts
  packages/augur-logger/src/logger.ts
  packages/augur-sdk/src/state/db/ZeroXOrders.ts
  packages/augur-ui/src/services/browser-mesh.ts
Labels: release/v2, type/chore

#7649 Change slippage multipliers to be sane
  packages/augur-artifacts/src/configuration.ts
  packages/augur-artifacts/src/environments/kovan.json
  packages/augur-artifacts/src/environments/mainnet.json
  packages/augur-ui/src/modules/swap/components/swap.tsx
Labels: type/bug

#7651 Sports Betting - My Account - My Created Markets
  packages/augur-ui/src/modules/account/components/account-view.styles.less
  packages/augur-ui/src/modules/account/components/account-view.tsx
  packages/augur-ui/src/modules/portfolio/components/markets/markets.styles.less
  packages/augur-ui/src/modules/portfolio/components/markets/markets.tsx
Labels: project/sportsbook

#7666 Outcomes table
  packages/augur-ui/src/modules/app/components/app.tsx
  packages/augur-ui/src/modules/events/actions/log-handlers.ts
  packages/augur-ui/src/modules/market-cards/common.tsx
  packages/augur-ui/src/modules/market-cards/containers/market-card.ts
  packages/augur-ui/src/modules/market-cards/market-card.tsx
  packages/augur-ui/src/modules/market-charts/containers/order-book.ts
  packages/augur-ui/src/modules/market/components/market-view/betting-market-view.styles.less
  packages/augur-ui/src/modules/market/components/market-view/betting-market-view.tsx
  packages/augur-ui/src/modules/market/components/market-view/market-view.tsx
  packages/augur-ui/src/modules/market/containers/market-view.ts
  packages/augur-ui/src/modules/markets-list/containers/markets-view-container.ts
  packages/augur-ui/src/modules/markets/store/constants.ts
  packages/augur-ui/src/modules/markets/store/markets-hooks.ts
  packages/augur-ui/src/modules/markets/store/markets.tsx
  packages/augur-ui/src/modules/orders/helpers/load-market-orderbook.ts
  packages/augur-ui/src/modules/orders/reducers/order-books.ts
  packages/augur-ui/src/reducers/index.ts
Labels: project/sportsbook

#7712 Add market infos
  packages/augur-ui/src/appStore/select-state.ts
  packages/augur-ui/src/modules/auth/actions/load-account-history.ts
  packages/augur-ui/src/modules/events/actions/log-handlers.ts
  packages/augur-ui/src/modules/market/containers/market-outcome.ts
  packages/augur-ui/src/modules/markets/actions/load-create-market-history.ts
  packages/augur-ui/src/modules/markets/actions/load-markets-info.ts
  packages/augur-ui/src/modules/markets/actions/update-markets-data.ts
  packages/augur-ui/src/modules/markets/reducers/market-infos.ts
  packages/augur-ui/src/modules/markets/selectors/market.ts
  packages/augur-ui/src/modules/markets/selectors/markets-all.ts
  packages/augur-ui/src/modules/markets/selectors/select-bucketed-price-time-series.ts
  packages/augur-ui/src/modules/markets/selectors/select-reporting-markets.ts
  packages/augur-ui/src/modules/markets/store/constants.ts
  packages/augur-ui/src/modules/markets/store/markets-hooks.ts
  packages/augur-ui/src/modules/notifications/selectors/notification-state.ts
  packages/augur-ui/src/modules/orders/actions/liquidity-management.ts
  packages/augur-ui/src/modules/orders/selectors/filled-orders.ts
  packages/augur-ui/src/modules/orders/selectors/user-open-orders.ts
  packages/augur-ui/src/modules/portfolio/containers/filled-order.ts
  packages/augur-ui/src/modules/portfolio/containers/open-order.ts
  packages/augur-ui/src/modules/portfolio/containers/position-row.ts
  packages/augur-ui/src/modules/positions/selectors/login-account-claimable-winnings.ts
  packages/augur-ui/src/modules/positions/selectors/login-account-positions.ts
  packages/augur-ui/src/modules/positions/selectors/select-reporting-winnings-by-market.ts
  packages/augur-ui/src/modules/trades/actions/place-market-trade.ts
  packages/augur-ui/src/modules/trades/actions/update-trade-cost-shares.ts
  packages/augur-ui/src/reducers/index.ts
Labels: project/sportsbook

#7715 Add missing things from order book and market info contexts
  packages/augur-ui/src/modules/auth/actions/load-account-reporting.ts
  packages/augur-ui/src/modules/market-charts/containers/order-book.ts
  packages/augur-ui/src/modules/market/containers/market-view.ts
  packages/augur-ui/src/modules/markets/actions/load-markets-info.ts
  packages/augur-ui/src/modules/orders/helpers/load-market-orderbook.ts
Labels: project/sportsbook

#7671 Update sports betting - my account - page layout
  packages/augur-ui/src/modules/account/components/account-view.styles.less
Labels: project/sportsbook

#7672 Sports Betting - Update Tooltip style
  packages/augur-ui/src/assets/styles/_typography.less
  packages/augur-ui/src/modules/common/tooltip.styles.less
Labels: project/sportsbook

#7742 fix market page loading
  packages/augur-ui/src/modules/market/components/market-view/market-view.tsx
  packages/augur-ui/src/modules/market/containers/market-view.ts
  packages/augur-ui/src/modules/markets/selectors/market.ts
Labels: project/sportsbook

#7744 fix some bugs on market view
  packages/augur-ui/src/modules/market-charts/containers/order-book.ts
  packages/augur-ui/src/modules/market/components/market-view/market-view.tsx
  packages/augur-ui/src/modules/orders/actions/pending-orders-management.ts
Labels: project/sportsbook

#7757 start removing container for market view, fix open orders loading
  packages/augur-ui/src/modules/create-market/components/form.tsx
  packages/augur-ui/src/modules/market-cards/common.tsx
  packages/augur-ui/src/modules/market/components/market-view/betting-market-view.tsx
  packages/augur-ui/src/modules/market/components/market-view/market-view.tsx
  packages/augur-ui/src/modules/market/containers/market-orders-positions-table.ts
  packages/augur-ui/src/modules/market/containers/market-view.ts
  packages/augur-ui/src/modules/orders/selectors/user-open-orders.ts
Labels: project/sportsbook

#7762 Context cleanup updates
  packages/augur-ui/src/appStore/index.ts
  packages/augur-ui/src/appStore/select-state.ts
  packages/augur-ui/src/main.tsx
  packages/augur-ui/src/modules/app/components/app.tsx
  packages/augur-ui/src/modules/app/containers/app.ts
  packages/augur-ui/src/modules/app/store/app-status-hooks.ts
  packages/augur-ui/src/modules/app/store/constants.ts
  packages/augur-ui/src/modules/app/store/pending-orders-hooks.ts
  packages/augur-ui/src/modules/app/store/pending-orders.tsx
  packages/augur-ui/src/modules/auth/actions/logout.ts
  packages/augur-ui/src/modules/auth/components/connect-dropdown/connect-dropdown.styles.less
  packages/augur-ui/src/modules/common/buttons.tsx
  packages/augur-ui/src/modules/events/actions/add-update-transaction.ts
  packages/augur-ui/src/modules/events/actions/liquidity-transactions.ts
  packages/augur-ui/src/modules/events/actions/log-handlers.ts
  packages/augur-ui/src/modules/markets/actions/submit-new-market.ts
  packages/augur-ui/src/modules/markets/selectors/markets-all.ts
  packages/augur-ui/src/modules/markets/selectors/user-markets.ts
  packages/augur-ui/src/modules/modal/containers/modal-claim-fees.ts
  packages/augur-ui/src/modules/modal/containers/modal-claim-markets-proceeds.ts
  packages/augur-ui/src/modules/modal/containers/modal-unsigned-orders.ts
  packages/augur-ui/src/modules/modal/unsigned-orders.tsx
  packages/augur-ui/src/modules/notifications/selectors/notification-state.ts
  packages/augur-ui/src/modules/orders/actions/liquidity-management.ts
  packages/augur-ui/src/modules/orders/actions/pending-orders-management.ts
  packages/augur-ui/src/modules/orders/reducers/liquidity-orders.ts
  packages/augur-ui/src/modules/orders/reducers/pending-orders.ts
  packages/augur-ui/src/modules/orders/selectors/user-open-orders.ts
  packages/augur-ui/src/modules/pending-queue/actions/pending-queue-management.ts
  packages/augur-ui/src/modules/pending-queue/reducers/pending-queue.ts
  packages/augur-ui/src/modules/portfolio/containers/my-bets-row.ts
  packages/augur-ui/src/modules/trading/containers/confirm.ts
  packages/augur-ui/src/modules/types.ts
  packages/augur-ui/src/reducers/index.ts
Labels: project/sportsbook

#7746 Restore ethereumjs-tx package
  packages/augur-sdk/package.json
  yarn.lock
Labels: type/chore

#7771 Orders context work
  packages/augur-ui/src/appStore/select-state.ts
  packages/augur-ui/src/modules/alerts/actions/set-alert-text.ts
  packages/augur-ui/src/modules/app/store/app-status-hooks.ts
  packages/augur-ui/src/modules/app/store/constants.ts
  packages/augur-ui/src/modules/auth/actions/load-account-history.ts
  packages/augur-ui/src/modules/events/actions/log-handlers.ts
  packages/augur-ui/src/modules/market-cards/containers/market-card.ts
  packages/augur-ui/src/modules/market/containers/market-header-reporting.ts
  packages/augur-ui/src/modules/market/containers/market-orders-positions-table.ts
  packages/augur-ui/src/modules/markets/actions/market-trading-history-management.ts
  packages/augur-ui/src/modules/markets/selectors/select-market-position-summary.ts
  packages/augur-ui/src/modules/orders/actions/load-account-open-orders.ts
  packages/augur-ui/src/modules/orders/actions/pending-orders-management.ts
  packages/augur-ui/src/modules/orders/reducers/filled-orders.ts
  packages/augur-ui/src/modules/orders/reducers/open-orders.ts
  packages/augur-ui/src/modules/orders/reducers/pending-orders.ts
  packages/augur-ui/src/modules/orders/selectors/filled-orders.ts
  packages/augur-ui/src/modules/orders/selectors/user-open-orders.ts
  packages/augur-ui/src/modules/portfolio/selectors/select-markets-filled-orders.ts
  packages/augur-ui/src/modules/positions/actions/account-positions.ts
  packages/augur-ui/src/modules/positions/actions/load-account-positions.ts
  packages/augur-ui/src/modules/positions/reducers/account-positions.ts
  packages/augur-ui/src/modules/positions/selectors/login-account-positions.ts
  packages/augur-ui/src/modules/trades/actions/place-market-trade.ts
  packages/augur-ui/src/modules/trades/actions/update-trade-cost-shares.ts
  packages/augur-ui/src/modules/trading/containers/wrapper.ts
  packages/augur-ui/src/reducers/index.ts
Labels: project/sportsbook

#7775 convert market trade history and reporting list state to context
  packages/augur-ui/src/appStore/select-state.ts
  packages/augur-ui/src/modules/auth/actions/load-account-history.ts
  packages/augur-ui/src/modules/events/actions/log-handlers.ts
  packages/augur-ui/src/modules/market-charts/containers/order-book.ts
  packages/augur-ui/src/modules/market/components/market-trade-history/market-trade-history.tsx
  packages/augur-ui/src/modules/market/components/market-view/betting-market-view.tsx
  packages/augur-ui/src/modules/market/components/market-view/market-view.tsx
  packages/augur-ui/src/modules/market/containers/market-outcome-trading-indicator.ts
  packages/augur-ui/src/modules/market/containers/market-trade-history.ts
  packages/augur-ui/src/modules/market/containers/market-view.ts
  packages/augur-ui/src/modules/markets/actions/load-markets.ts
  packages/augur-ui/src/modules/markets/actions/market-trading-history-management.ts
  packages/augur-ui/src/modules/markets/actions/update-markets-data.ts
  packages/augur-ui/src/modules/markets/reducers/market-trading-history.ts
  packages/augur-ui/src/modules/markets/selectors/select-reporting-markets.ts
  packages/augur-ui/src/modules/markets/store/constants.ts
  packages/augur-ui/src/modules/markets/store/markets-hooks.ts
  packages/augur-ui/src/modules/markets/store/markets.tsx
  packages/augur-ui/src/modules/reporting/actions/update-reporting-list.ts
  packages/augur-ui/src/modules/reporting/containers/markets-in-dispute.ts
  packages/augur-ui/src/modules/reporting/containers/reporting-list.ts
  packages/augur-ui/src/modules/reporting/reducers/reporting-list-state.ts
  packages/augur-ui/src/reducers/index.ts
Labels: project/sportsbook

#7785 fix reporting loading
  packages/augur-ui/src/modules/markets/selectors/select-reporting-markets.ts
  packages/augur-ui/src/modules/reporting/containers/markets-in-dispute.ts
  packages/augur-ui/src/modules/reporting/containers/reporting-list.ts
  packages/augur-ui/src/modules/reporting/reporting-list.tsx
Labels: project/sportsbook

#7753 Fix layout and search bar Sportsbook accounts touchups
  packages/augur-ui/src/assets/styles/_typography.less
  packages/augur-ui/src/modules/account/components/account-view.styles.less
  packages/augur-ui/src/modules/account/components/notifications.tsx
  packages/augur-ui/src/modules/account/components/open-markets.tsx
  packages/augur-ui/src/modules/account/components/stats.styles.less
  packages/augur-ui/src/modules/common/icons.tsx
  packages/augur-ui/src/modules/common/search.styles.less
  packages/augur-ui/src/modules/portfolio/components/common/empty-display.styles.less
  packages/augur-ui/src/modules/portfolio/components/common/empty-display.tsx
  packages/augur-ui/src/modules/portfolio/components/common/filter-box.tsx
  packages/augur-ui/src/modules/portfolio/components/common/filter-switch-box.tsx
  packages/augur-ui/src/modules/portfolio/components/common/quad-box.tsx
  packages/augur-ui/src/modules/portfolio/components/favorites/favorites.tsx
  packages/augur-ui/src/modules/portfolio/components/markets/markets.styles.less
  packages/augur-ui/src/modules/portfolio/components/markets/markets.tsx
  packages/augur-ui/src/modules/reporting/components/markets-in-dispute.tsx
Labels: project/sportsbook

#7803 Convert disputing to pure component
  packages/augur-ui/src/modules/reporting/components/markets-in-dispute.tsx
  packages/augur-ui/src/modules/reporting/containers/markets-in-dispute.ts
Labels: project/sportsbook

#7828 Mobile menus
  packages/augur-ui/src/modules/app/components/app.styles.less
  packages/augur-ui/src/modules/app/components/help-resources.styles.less
  packages/augur-ui/src/modules/app/components/inner-nav/inner-nav.styles.less
  packages/augur-ui/src/modules/app/components/odds-menu.styles.less
  packages/augur-ui/src/modules/app/components/side-nav/side-nav.styles.less
  packages/augur-ui/src/modules/app/components/theme-switch.styles.less
  packages/augur-ui/src/modules/app/components/top-bar.styles.less
  packages/augur-ui/src/modules/app/components/top-nav/top-nav.styles.less
  packages/augur-ui/src/modules/auth/components/connect-account/connect-account.styles.less
  packages/augur-ui/src/modules/auth/components/connect-account/connect-account.tsx
  packages/augur-ui/src/modules/auth/components/connect-dropdown/connect-dropdown.styles.less
  packages/augur-ui/src/modules/markets-list/components/markets-header.styles.less
  packages/augur-ui/src/modules/markets-list/components/markets-header.tsx
  packages/augur-ui/src/modules/markets-list/components/markets-view.styles.less
  packages/augur-ui/src/modules/markets-list/components/markets-view.tsx
  packages/augur-ui/src/modules/trading/betslip.styles.less
Labels: project/sportsbook

#7835 fix hover styles for desktop and mobile in top bar
  packages/augur-ui/src/modules/alerts/components/alerts-view.styles.less
  packages/augur-ui/src/modules/app/components/odds-menu.styles.less
  packages/augur-ui/src/modules/app/components/top-bar.styles.less
  packages/augur-ui/src/modules/auth/components/connect-account/connect-account.styles.less
Labels: project/sportsbook

#7837 switch up mobile my bets menu
  packages/augur-ui/src/modules/common/constants.ts
  packages/augur-ui/src/modules/portfolio/components/common/my-bets-inner-nav.tsx
Labels: project/sportsbook

#7858 Responsive betslip updates
  packages/augur-ui/src/modules/trading/betslip.styles.less
  packages/augur-ui/src/modules/trading/betslip.tsx
Labels: project/sportsbook

#7863 remove dispatch and containers from alerts
  packages/augur-ui/src/modules/alerts/actions/alerts.ts
  packages/augur-ui/src/modules/alerts/actions/set-alert-text.ts
  packages/augur-ui/src/modules/alerts/components/alerts-view.tsx
  packages/augur-ui/src/modules/alerts/components/toasts-view.tsx
  packages/augur-ui/src/modules/alerts/containers/alerts-view.ts
  packages/augur-ui/src/modules/alerts/containers/toasts-view.ts
  packages/augur-ui/src/modules/app/components/app.tsx
  packages/augur-ui/src/modules/auth/actions/load-account-data-from-local-storage.ts
  packages/augur-ui/src/modules/auth/actions/update-assets.ts
  packages/augur-ui/src/modules/auth/actions/update-sdk.ts
  packages/augur-ui/src/modules/events/actions/add-update-transaction.ts
  packages/augur-ui/src/modules/events/actions/log-handlers.ts
  packages/augur-ui/src/modules/market/components/market-view/market-view.tsx
  packages/augur-ui/src/modules/market/containers/market-view.ts
  packages/augur-ui/src/modules/markets/actions/load-markets-info.ts
  packages/augur-ui/src/modules/markets/store/markets-hooks.ts
  packages/augur-ui/src/modules/universe/actions/load-forking-info.ts
Labels: project/sportsbook

#7864 Post context cleanups
  packages/augur-ui/src/modules/account/actions/update-platform-timeframe-data.ts
  packages/augur-ui/src/modules/account/actions/update-timeframe-data.ts
  packages/augur-ui/src/modules/account/components/account-view.tsx
  packages/augur-ui/src/modules/account/components/activity.tsx
  packages/augur-ui/src/modules/account/components/augur-status.tsx
  packages/augur-ui/src/modules/account/components/open-markets.tsx
  packages/augur-ui/src/modules/account/components/overview-chart.tsx
  packages/augur-ui/src/modules/account/components/overview.tsx
  packages/augur-ui/src/modules/account/components/profit-loss-chart.tsx
  packages/augur-ui/src/modules/account/components/stats.tsx
  packages/augur-ui/src/modules/account/components/transactions.tsx
  packages/augur-ui/src/modules/account/containers/activity.ts
  packages/augur-ui/src/modules/account/containers/notifications.ts
  packages/augur-ui/src/modules/account/containers/open-markets.ts
  packages/augur-ui/src/modules/account/containers/overview-chart.ts
  packages/augur-ui/src/modules/account/containers/platform-overview-stats.ts
  packages/augur-ui/src/modules/account/containers/stats.ts
  packages/augur-ui/src/modules/account/containers/transactions.ts
  packages/augur-ui/src/modules/account/selectors/has-stake-in-market.ts
  packages/augur-ui/src/modules/market-cards/common.tsx
  packages/augur-ui/src/modules/market-cards/containers/market-card.ts
  packages/augur-ui/src/modules/market-cards/market-card.tsx
  packages/augur-ui/src/modules/markets-list/components/markets-list.tsx
  packages/augur-ui/src/modules/notifications/selectors/notification-state.ts
  packages/augur-ui/src/modules/positions/actions/get-profit-loss.ts
  packages/augur-ui/src/modules/positions/selectors/login-account-claimable-winnings.ts
  packages/augur-ui/src/modules/reporting/common.tsx
  packages/augur-ui/src/modules/reporting/components/markets-in-dispute.tsx
  packages/augur-ui/src/services/analytics/helpers.ts
Labels: project/sportsbook

#7866 Sportsbook account page responsive - tablet
  packages/augur-ui/src/modules/account/components/account-view.styles.less
  packages/augur-ui/src/modules/account/components/account-view.tsx
  packages/augur-ui/src/modules/app/components/app.styles.less
Labels: project/sportsbook

#7878 Rm portfolio containers
  packages/augur-ui/src/modules/account/components/account-view.tsx
  packages/augur-ui/src/modules/account/components/open-markets.tsx
  packages/augur-ui/src/modules/app/actions/init-augur.ts
  packages/augur-ui/src/modules/auth/actions/login-with-injected-web3.ts
  packages/augur-ui/src/modules/create-market/fees-liquidity.tsx
  packages/augur-ui/src/modules/events/actions/log-handlers.ts
  packages/augur-ui/src/modules/markets/actions/market-creator-fees-management.ts
  packages/augur-ui/src/modules/markets/actions/submit-new-market.ts
  packages/augur-ui/src/modules/modal/actions/close-modal.ts
  packages/augur-ui/src/modules/portfolio/components/common/filter-box.tsx
  packages/augur-ui/src/modules/portfolio/components/common/market-row.tsx
  packages/augur-ui/src/modules/portfolio/components/markets/markets.tsx
  packages/augur-ui/src/modules/portfolio/components/orders/filled-orders.tsx
  packages/augur-ui/src/modules/portfolio/components/orders/open-orders.tsx
  packages/augur-ui/src/modules/portfolio/components/portfolio-view/portfolio-view.tsx
  packages/augur-ui/src/modules/portfolio/components/positions/positions.tsx
  packages/augur-ui/src/modules/portfolio/containers/filled-orders.ts
  packages/augur-ui/src/modules/portfolio/containers/filter-switch-box.ts
  packages/augur-ui/src/modules/portfolio/containers/market-row.ts
  packages/augur-ui/src/modules/portfolio/containers/my-markets.ts
  packages/augur-ui/src/modules/portfolio/containers/open-orders.ts
  packages/augur-ui/src/modules/portfolio/containers/positions.ts
Labels: project/sportsbook

#7880 fix discard modal showing during creation and pending market creation
  packages/augur-ui/src/modules/create-market/components/form.tsx
  packages/augur-ui/src/modules/markets/selectors/markets-all.ts
  packages/augur-ui/src/modules/markets/selectors/user-markets.ts
Labels: project/sportsbook

#7883 Rm portfolio containers
  packages/augur-ui/src/modules/account/components/account-view.tsx
  packages/augur-ui/src/modules/market/components/market-view/market-view.tsx
  packages/augur-ui/src/modules/market/containers/market-view.ts
  packages/augur-ui/src/modules/portfolio/components/common/filter-box.tsx
  packages/augur-ui/src/modules/portfolio/components/favorites/favorites.tsx
  packages/augur-ui/src/modules/portfolio/components/markets/markets.tsx
  packages/augur-ui/src/modules/portfolio/components/positions/positions.tsx
  packages/augur-ui/src/modules/portfolio/containers/favorites.ts
  packages/augur-ui/src/modules/portfolio/containers/filter-box.ts
  packages/augur-ui/src/modules/routes/constants/components.ts
Labels: project/sportsbook

#7895 fixed a broken import
  packages/augur-ui/src/modules/account/components/overview.tsx
Labels: project/sportsbook

#7901 update mobile styles on bettting ui in modals
  packages/augur-ui/src/modules/app/components/help-resources.styles.less
  packages/augur-ui/src/modules/app/components/inner-nav/category-filters.styles.less
  packages/augur-ui/src/modules/app/components/inner-nav/markets-list-filters.styles.less
  packages/augur-ui/src/modules/markets-list/components/markets-view.styles.less
  packages/augur-ui/src/modules/modal/message.tsx
  packages/augur-ui/src/modules/modal/modal.styles.less
Labels: project/sportsbook

#7902 Cleanup redux even more
  packages/augur-ui/src/modules/auth/actions/load-account-data-from-local-storage.ts
  packages/augur-ui/src/modules/auth/actions/update-assets.ts
  packages/augur-ui/src/modules/auth/actions/update-sdk.ts
  packages/augur-ui/src/modules/common/buttons.tsx
  packages/augur-ui/src/modules/contracts/actions/contractCalls.ts
  packages/augur-ui/src/modules/create-market/actions/get-category-stats.ts
  packages/augur-ui/src/modules/events/actions/add-update-transaction.ts
  packages/augur-ui/src/modules/events/actions/listen-to-updates.ts
  packages/augur-ui/src/modules/events/actions/log-handlers.ts
  packages/augur-ui/src/modules/filter-sort/components/filter-dropdowns.tsx
  packages/augur-ui/src/modules/filter-sort/components/filter-search.tsx
  packages/augur-ui/src/modules/filter-sort/containers/filter-dropdowns.ts
  packages/augur-ui/src/modules/filter-sort/containers/filter-search.ts
  packages/augur-ui/src/modules/market-cards/common.tsx
  packages/augur-ui/src/modules/market/components/common/common.tsx
  packages/augur-ui/src/modules/market/components/common/social-media-buttons.tsx
  packages/augur-ui/src/modules/market/containers/market-orders-positions-table.ts
  packages/augur-ui/src/modules/market/containers/social-media-buttons.ts
  packages/augur-ui/src/modules/markets-list/components/markets-header.tsx
  packages/augur-ui/src/modules/markets-list/components/markets-view.tsx
  packages/augur-ui/src/modules/markets-list/containers/markets-landing-page-container.ts
  packages/augur-ui/src/modules/markets/actions/load-markets-info.ts
  packages/augur-ui/src/modules/markets/actions/update-new-market.ts
  packages/augur-ui/src/modules/markets/actions/update-outcome-price.ts
  packages/augur-ui/src/modules/modal/containers/modal-reporting.ts
  packages/augur-ui/src/modules/orders/actions/cancel-order.ts
  packages/augur-ui/src/modules/orders/actions/load-account-open-orders.ts
  packages/augur-ui/src/modules/pending-queue/actions/pending-queue-management.ts
  packages/augur-ui/src/modules/portfolio/components/common/filter-box.tsx
  packages/augur-ui/src/modules/portfolio/components/favorites/favorites.tsx
  packages/augur-ui/src/modules/portfolio/components/portfolio-view/my-bets.tsx
  packages/augur-ui/src/modules/portfolio/containers/open-order.ts
  packages/augur-ui/src/modules/positions/actions/load-account-positions.ts
  packages/augur-ui/src/modules/reporting/actions/participation-tokens-management.ts
  packages/augur-ui/src/modules/reporting/common.tsx
  packages/augur-ui/src/modules/trading/containers/confirm.ts
  packages/augur-ui/src/services/analytics/helpers.ts
Labels: project/sportsbook
