Repository AugurProject/augur, pull requests merged in 2020-07, with the labels that each got.

#8271 fix issue where best offer was traded and emitting new best offer
  packages/augur-sdk/src/api/BestOffer.ts
Labels: project/sportsbook

#8270 update my bets to use real data
  packages/augur-ui/src/modules/common/table-rows.tsx
  packages/augur-ui/src/modules/portfolio/components/common/common.tsx
  packages/augur-ui/src/modules/portfolio/components/portfolio-view/my-bets.tsx
  packages/augur-ui/src/modules/portfolio/store/constants.ts
  packages/augur-ui/src/modules/portfolio/store/my-bets-hooks.ts
  packages/augur-ui/src/modules/portfolio/store/my-bets.tsx
  packages/augur-ui/src/modules/trading/store/constants.ts
Labels: project/sportsbook

#8272 Update social-media-buttons.tsx
  packages/augur-ui/src/modules/market/components/common/social-media-buttons.tsx
Labels: type/bug

#8280 add market links
  packages/augur-ui/src/modules/common/row-column.tsx
  packages/augur-ui/src/modules/common/table-rows.tsx
  packages/augur-ui/src/modules/market-cards/common.tsx
  packages/augur-ui/src/modules/portfolio/components/common/common.tsx
Labels: project/sportsbook

#8307 fix notification bugs, consolidate cashout button
  packages/augur-ui/src/modules/account/components/notifications.tsx
  packages/augur-ui/src/modules/common/buttons.tsx
  packages/augur-ui/src/modules/common/row-column.tsx
  packages/augur-ui/src/modules/markets/actions/load-markets.ts
  packages/augur-ui/src/modules/portfolio/components/common/common.tsx
  packages/augur-ui/src/modules/portfolio/components/portfolio-view/my-bets.tsx
  packages/augur-ui/src/modules/trading/common.tsx
Labels: project/sportsbook

#8320 fix broken claim modal
  packages/augur-ui/src/modules/modal/shared-modals.tsx
Labels: project/sportsbook

#8322 add actions to my bets
  packages/augur-ui/src/modules/common/buttons.tsx
Labels: project/sportsbook

#8349 Catch liquidity pools
  packages/augur-ui/src/modules/app/store/app-status-hooks.ts
  packages/augur-ui/src/modules/app/store/pending-orders-hooks.ts
  packages/augur-ui/src/modules/events/actions/log-handlers.ts
  packages/augur-ui/src/modules/market-cards/common.styles.less
  packages/augur-ui/src/modules/market-cards/common.tsx
  packages/augur-ui/src/modules/market-cards/market-card.styles.less
  packages/augur-ui/src/modules/market-cards/sports-market-card.tsx
  packages/augur-ui/src/modules/market/components/common/common.tsx
  packages/augur-ui/src/modules/market/components/market-header/market-header.tsx
  packages/augur-ui/src/modules/market/components/market-view/market-view.tsx
  packages/augur-ui/src/modules/markets-list/components/markets-list.tsx
  packages/augur-ui/src/modules/markets-list/components/markets-view.tsx
  packages/augur-ui/src/modules/markets/store/constants.ts
  packages/augur-ui/src/modules/markets/store/markets-hooks.ts
  packages/augur-ui/src/modules/modal/signin.tsx
  packages/augur-ui/src/modules/trading/store/betslip-hooks.ts
Labels: project/sportsbook

#8353 small-correction
  packages/augur-ui/src/modules/market-cards/common.tsx
  packages/augur-ui/src/modules/trading/components/confirm.tsx
Labels: project/sportsbook

#8355 add null check for best offer from getter
  packages/augur-artifacts/src/environments/demo.json
  packages/augur-artifacts/src/environments/kovan.json
  packages/augur-sdk/src/api/BestOffer.ts
  packages/augur-ui/src/modules/events/actions/log-handlers.ts
  packages/augur-ui/src/modules/positions/actions/load-account-positions.ts
Labels: project/sportsbook

#8366 add missing references
  packages/augur-ui/src/modules/market/components/market-view/market-view.tsx
  packages/augur-ui/src/modules/trading/components/confirm.tsx
Labels: project/sportsbook

#8444 Gh 8273 adjustments to sdk server for automated warp reporting
  .dockerignore
  .gitignore
  packages/augur-sdk-lite/src/AugurLite.ts
  packages/augur-sdk-lite/src/constants.ts
  packages/augur-sdk/certs/ssl-cert-snakeoil.key
  packages/augur-sdk/certs/ssl-cert-snakeoil.pem
  packages/augur-sdk/src/Augur.ts
  packages/augur-sdk/src/connector/single-thread-connector.ts
  packages/augur-sdk/src/state/create-api.ts
  packages/augur-sdk/src/state/getter/Router.ts
  packages/augur-sdk/src/state/getter/WarpSyncGetter.ts
  packages/augur-sdk/src/state/settings.json
  packages/augur-sdk/src/state/sync/WarpSyncStrategy.ts
  packages/augur-sdk/src/state/test-connector.ts
  packages/augur-sdk/tsconfig.json
  packages/augur-test/src/tests/state/getter/markets/misc.test.ts
  packages/augur-test/src/tests/warp/WarpSyncMarkets.test.ts
  packages/augur-tools/package.json
  packages/augur-tools/src/flash/cli.ts
  packages/augur-tools/src/flash/scripts.ts
  packages/augur-tools/src/flash/warp-sync.ts
  yarn.lock
Labels: project/trading

#8687 Reporting only is just a build env now
  .azure-templates/ui-build-to-s3.yml
  azure-pipelines.yml
  packages/augur-artifacts/src/environments/reporting.json
  packages/augur-ui/config/webpack.common.config.js
Labels: release/v2.0

#8707 Dont show transfer dust value
  packages/augur-ui/src/modules/auth/actions/update-assets.ts
  packages/augur-ui/src/modules/auth/containers/connect-dropdown.ts
  packages/augur-ui/src/modules/modal/containers/modal-buy-dai.ts
Labels: type/bug

#8734 remove gsn from install.sh
  support/install.sh
Labels: status/wip
