Repository AugurProject/augur, pull requests merged in 2020-06, with the labels that each got.

#7911 Sportsbook - Alerts Touchups
  packages/augur-ui/src/assets/styles/_typography.less
  packages/augur-ui/src/modules/alerts/components/alert.styles.less
  packages/augur-ui/src/modules/alerts/components/alerts-view.styles.less
  packages/augur-ui/src/modules/alerts/components/alerts-view.tsx
  packages/augur-ui/src/modules/app/components/top-bar.styles.less
Labels: project/sportsbook

#7919 convert market views to remove redux
  packages/augur-ui/src/modules/markets-list/actions/update-login-account-settings.ts
  packages/augur-ui/src/modules/markets-list/components/markets-landing-page.tsx
  packages/augur-ui/src/modules/markets-list/components/markets-view.tsx
  packages/augur-ui/src/modules/markets-list/containers/markets-landing-page-container.ts
  packages/augur-ui/src/modules/markets-list/containers/markets-view-container.ts
  packages/augur-ui/src/modules/routes/constants/components.ts
Labels: project/sportsbook

#7920 Updating loginaccount
  packages/augur-ui/src/modules/account/components/transactions.tsx
  packages/augur-ui/src/modules/app/store/constants.ts
  packages/augur-ui/src/modules/auth/actions/update-assets.ts
  packages/augur-ui/src/modules/auth/connect-dropdown.tsx
  packages/augur-ui/src/modules/auth/helpers/get-eth-reserve.ts
  packages/augur-ui/src/modules/modal/containers/modal-transfer.ts
  packages/augur-ui/src/modules/types.ts
Labels: project/sportsbook

#7924 convert table row containers
  packages/augur-ui/src/modules/common/table-rows.tsx
  packages/augur-ui/src/modules/market/components/market-orders-positions-table/filled-orders-table.tsx
  packages/augur-ui/src/modules/market/components/market-orders-positions-table/open-orders-table.tsx
  packages/augur-ui/src/modules/market/components/market-outcomes-list/market-outcomes-list.tsx
  packages/augur-ui/src/modules/market/containers/market-outcome.ts
  packages/augur-ui/src/modules/portfolio/components/common/common.tsx
  packages/augur-ui/src/modules/portfolio/components/common/market-positions-table.tsx
  packages/augur-ui/src/modules/portfolio/components/common/order-market-row.tsx
  packages/augur-ui/src/modules/portfolio/components/orders/filled-orders.tsx
  packages/augur-ui/src/modules/portfolio/components/orders/open-orders.tsx
  packages/augur-ui/src/modules/portfolio/containers/filled-order.ts
  packages/augur-ui/src/modules/portfolio/containers/my-bets-row.ts
  packages/augur-ui/src/modules/portfolio/containers/open-order.ts
  packages/augur-ui/src/modules/portfolio/containers/position-row.ts
Labels: project/sportsbook

#7933 Sportsbook - update filter-search in markets-view
  packages/augur-ui/src/modules/filter-sort/components/filter-dropdowns.styles.less
  packages/augur-ui/src/modules/filter-sort/components/filter-search.styles.less
  packages/augur-ui/src/modules/markets-list/components/markets-view.styles.less
Labels: project/sportsbook

#7943 Convert reporting and fix payload bug
  packages/augur-ui/src/modules/common/progress.tsx
  packages/augur-ui/src/modules/market-cards/common.tsx
  packages/augur-ui/src/modules/markets-list/components/markets-landing-page.tsx
  packages/augur-ui/src/modules/markets-list/components/markets-view.tsx
  packages/augur-ui/src/modules/markets/actions/load-markets.ts
  packages/augur-ui/src/modules/markets/actions/update-markets-data.ts
  packages/augur-ui/src/modules/markets/store/markets-hooks.ts
  packages/augur-ui/src/modules/reporting/containers/disputing-window-progress.ts
  packages/augur-ui/src/modules/reporting/containers/reporting.ts
  packages/augur-ui/src/modules/reporting/disputing.tsx
  packages/augur-ui/src/modules/reporting/reporting.tsx
  packages/augur-ui/src/modules/routes/constants/components.ts
  packages/augur-ui/src/modules/universe-cards/actions/switch-universe.ts
Labels: project/sportsbook

#7951 Convert reporting
  packages/augur-ui/src/modules/app/components/app.tsx
  packages/augur-ui/src/modules/common/form.tsx
  packages/augur-ui/src/modules/events/actions/log-handlers.ts
  packages/augur-ui/src/modules/market-cards/common.tsx
  packages/augur-ui/src/modules/markets/actions/load-markets.ts
  packages/augur-ui/src/modules/markets/store/markets-hooks.ts
  packages/augur-ui/src/modules/modal/containers/modal-reporting.ts
  packages/augur-ui/src/modules/modal/reporting.tsx
  packages/augur-ui/src/modules/reporting/actions/update-reporting-list.ts
  packages/augur-ui/src/modules/reporting/common.tsx
  packages/augur-ui/src/modules/reporting/components/markets-in-dispute.tsx
  packages/augur-ui/src/modules/reporting/containers/disputing-bonds-view.ts
  packages/augur-ui/src/modules/reporting/containers/forking-banner.ts
  packages/augur-ui/src/modules/reporting/containers/markets-in-dispute.ts
  packages/augur-ui/src/modules/reporting/containers/participation-tokens-view.ts
  packages/augur-ui/src/modules/reporting/containers/releasable-rep-notice.ts
  packages/augur-ui/src/modules/reporting/containers/reporting-bonds-view.ts
  packages/augur-ui/src/modules/reporting/containers/reporting-card.ts
  packages/augur-ui/src/modules/reporting/containers/reporting-list.ts
  packages/augur-ui/src/modules/reporting/disputing.tsx
  packages/augur-ui/src/modules/reporting/forking-banner.tsx
  packages/augur-ui/src/modules/reporting/reporting-list.tsx
  packages/augur-ui/src/modules/reporting/reporting.tsx
Labels: project/sportsbook

#7946 More cleanup work
  packages/augur-ui/src/appStore/select-state.ts
  packages/augur-ui/src/modules/account/components/account-view.tsx
  packages/augur-ui/src/modules/account/components/notifications.tsx
  packages/augur-ui/src/modules/app/components/app.tsx
  packages/augur-ui/src/modules/app/components/top-bar.styles.less
  packages/augur-ui/src/modules/filter-sort/filter-dropdowns.styles.less
  packages/augur-ui/src/modules/filter-sort/filter-dropdowns.tsx
  packages/augur-ui/src/modules/filter-sort/filter-search.styles.less
  packages/augur-ui/src/modules/filter-sort/filter-search.tsx
  packages/augur-ui/src/modules/filter-sort/market-card-format-switcher.styles.less
  packages/augur-ui/src/modules/filter-sort/market-card-format-switcher.tsx
  packages/augur-ui/src/modules/filter-sort/market-type-filter.styles.less
  packages/augur-ui/src/modules/filter-sort/market-type-filter.tsx
  packages/augur-ui/src/modules/markets-list/components/markets-header.tsx
  packages/augur-ui/src/modules/markets-list/components/markets-view.tsx
  packages/augur-ui/src/modules/markets/selectors/select-bucketed-price-time-series.ts
  packages/augur-ui/src/modules/markets/selectors/select-reporting-markets.ts
  packages/augur-ui/src/modules/markets/selectors/select-user-market-positions.ts
  packages/augur-ui/src/modules/markets/selectors/user-markets.ts
  packages/augur-ui/src/modules/modal/containers/modal-buy-dai.ts
  packages/augur-ui/src/modules/notifications/selectors/notification-state.ts
  packages/augur-ui/src/modules/orders/helpers/load-market-orderbook.ts
  packages/augur-ui/src/modules/portfolio/components/portfolio-view/my-bets.tsx
  packages/augur-ui/src/modules/portfolio/selectors/select-markets-filled-orders.ts
  packages/augur-ui/src/modules/portfolio/selectors/select-markets-open-orders.ts
  packages/augur-ui/src/modules/portfolio/selectors/select-markets-positions-recently-traded.ts
  packages/augur-ui/src/modules/positions/selectors/login-account-positions.ts
  packages/augur-ui/src/modules/positions/selectors/login-account-totals.ts
  packages/augur-ui/src/modules/positions/selectors/positions-summary.ts
  packages/augur-ui/src/modules/positions/selectors/select-reporting-winnings-by-market.ts
Labels: project/sportsbook

#7959 Clean trding pg
  packages/augur-ui/src/modules/account/components/notifications-templates.tsx
  packages/augur-ui/src/modules/common/row-column.tsx
  packages/augur-ui/src/modules/market-cards/market-card.tsx
  packages/augur-ui/src/modules/market/components/common/market-title.tsx
  packages/augur-ui/src/modules/market/components/common/outcome-trading-indicator/outcome-trading-indicator.tsx
  packages/augur-ui/src/modules/market/components/market-header/market-header-reporting.tsx
  packages/augur-ui/src/modules/market/components/market-header/market-header.tsx
  packages/augur-ui/src/modules/market/components/market-orders-positions-table/market-orders-positions-table.tsx
  packages/augur-ui/src/modules/market/components/market-outcomes-list/market-outcomes-list.tsx
  packages/augur-ui/src/modules/market/components/market-scalar-outcome-display/market-scalar-outcome-display.tsx
  packages/augur-ui/src/modules/market/components/market-view/market-view.tsx
  packages/augur-ui/src/modules/market/containers/market-header-reporting.ts
  packages/augur-ui/src/modules/market/containers/market-header.ts
  packages/augur-ui/src/modules/market/containers/market-orders-positions-table.ts
  packages/augur-ui/src/modules/market/containers/market-outcome-trading-indicator.ts
  packages/augur-ui/src/modules/market/containers/market-outcomes-list.ts
  packages/augur-ui/src/modules/market/containers/market-title.ts
  packages/augur-ui/src/modules/market/containers/positions-table.ts
  packages/augur-ui/src/modules/portfolio/components/common/filled-orders-table.tsx
  packages/augur-ui/src/modules/portfolio/components/common/market-positions-table.tsx
  packages/augur-ui/src/modules/portfolio/components/common/market-row.tsx
  packages/augur-ui/src/modules/portfolio/components/common/open-order-expanded-content.tsx
  packages/augur-ui/src/modules/portfolio/components/common/order-market-row.tsx
  packages/augur-ui/src/modules/portfolio/components/positions/positions.tsx
  packages/augur-ui/src/modules/reporting/common.tsx
Labels: project/sportsbook

#7964 Convert more
  packages/augur-ui/src/modules/create-market/components/common.tsx
  packages/augur-ui/src/modules/create-market/fees-liquidity.tsx
  packages/augur-ui/src/modules/market-cards/containers/migrate-market-notice.ts
  packages/augur-ui/src/modules/market-cards/market-card.tsx
  packages/augur-ui/src/modules/market-charts/components/order-book/order-book.tsx
  packages/augur-ui/src/modules/market-charts/containers/order-book.ts
  packages/augur-ui/src/modules/market/components/market-header/market-header-reporting.tsx
  packages/augur-ui/src/modules/market/components/market-view/market-view.tsx
Labels: project/sportsbook

#7980 Depth chart
  packages/augur-ui/src/modules/create-market/fees-liquidity.tsx
  packages/augur-ui/src/modules/market-charts/components/candlestick/candlestick-highchart.tsx
  packages/augur-ui/src/modules/market-charts/components/candlestick/outcome-candlestick.tsx
  packages/augur-ui/src/modules/market-charts/components/depth/depth.tsx
  packages/augur-ui/src/modules/market-charts/components/market-charts-pane/market-charts-pane.tsx
  packages/augur-ui/src/modules/market-charts/components/price-history/price-history.tsx
  packages/augur-ui/src/modules/market-charts/containers/candlestick-highchart.ts
  packages/augur-ui/src/modules/market-charts/containers/depth.ts
  packages/augur-ui/src/modules/market-charts/containers/market-charts-pane.ts
  packages/augur-ui/src/modules/market-charts/containers/price-history.ts
  packages/augur-ui/src/modules/market/components/common/common.tsx
  packages/augur-ui/src/modules/market/components/market-header/market-header.tsx
  packages/augur-ui/src/modules/market/components/market-view/market-view.tsx
Labels: project/sportsbook

#8015 close-modal-quick-fix
  packages/augur-ui/src/modules/modal/gas.tsx
Labels: project/sportsbook

#8027 Modals rm
  packages/augur-ui/src/modules/modal/add-funds.tsx
  packages/augur-ui/src/modules/modal/cash-out-form.tsx
  packages/augur-ui/src/modules/modal/components/modal-view.tsx
  packages/augur-ui/src/modules/modal/containers/modal-add-funds.ts
  packages/augur-ui/src/modules/modal/containers/modal-cash-out.ts
  packages/augur-ui/src/modules/modal/containers/modal-scalar.ts
  packages/augur-ui/src/modules/modal/scalar.tsx
Labels: project/sportsbook

#8042 Merge master 6 15 2020
  packages/augur-artifacts/src/templates.ts
  packages/augur-sdk/src/api/GSN.ts
  packages/augur-sdk/src/api/ZeroX.ts
  packages/augur-sdk/src/constants.ts
  packages/augur-sdk/src/lib/contract-deps/ContractDependenciesGSN.ts
  packages/augur-sdk/src/state/db/MarketDB.ts
  packages/augur-sdk/src/state/getter/Markets.ts
  packages/augur-sdk/src/state/logs/types.ts
  packages/augur-sdk/src/state/sync/WarpSyncStrategy.ts
  packages/augur-test/src/tests/api/Betting.test.ts
  packages/augur-test/src/tests/state/getter/users/get-profit-loss-and-summary.test.ts
  packages/augur-test/src/tests/templates/validations.test.ts
  packages/augur-tools/src/flash/data/canned-markets.ts
  packages/augur-tools/src/flash/generate-templates.ts
  packages/augur-tools/src/templates-source.ts
  packages/augur-tools/src/templates-template.ts
  packages/augur-ui/src/assets/styles/_colors.less
  packages/augur-ui/src/assets/styles/_misc_redesign.less
  packages/augur-ui/src/modules/app/actions/check-if-mainnet.ts
  packages/augur-ui/src/modules/app/actions/load-gas-price-info.ts
  packages/augur-ui/src/modules/app/components/inner-nav/base-inner-nav-pure.tsx
  packages/augur-ui/src/modules/app/components/inner-nav/inner-nav.styles.less
  packages/augur-ui/src/modules/app/components/inner-nav/markets-list-filters.tsx
  packages/augur-ui/src/modules/app/components/side-nav/side-nav.styles.less
  packages/augur-ui/src/modules/common/buttons.styles.less
  packages/augur-ui/src/modules/common/constants.ts
  packages/augur-ui/src/modules/common/form.tsx
  packages/augur-ui/src/modules/common/labels.tsx
  packages/augur-ui/src/modules/common/tooltip.styles.less
  packages/augur-ui/src/modules/common/validations.ts
  packages/augur-ui/src/modules/create-market/components/common.styles.less
  packages/augur-ui/src/modules/create-market/components/common.tsx
  packages/augur-ui/src/modules/create-market/components/create-market-view/create-market-view.styles.less
  packages/augur-ui/src/modules/create-market/components/form.tsx
  packages/augur-ui/src/modules/create-market/constants.ts
  packages/augur-ui/src/modules/create-market/get-template.ts
  packages/augur-ui/src/modules/create-market/landing.styles.less
  packages/augur-ui/src/modules/events/actions/log-handlers.ts
  packages/augur-ui/src/modules/market-cards/common.tsx
  packages/augur-ui/src/modules/market/components/market-header/market-header-reporting.tsx
  packages/augur-ui/src/modules/modal/containers/modal-tutorial-intro.ts
  packages/augur-ui/src/modules/modal/message.tsx
  packages/augur-ui/src/modules/modal/modal.styles.less
  packages/augur-ui/src/modules/modal/reporting.tsx
  packages/augur-ui/src/modules/trading/components/form.tsx
  packages/augur-ui/src/utils/convert-marketInfo-marketData.ts
  packages/augur-ui/src/utils/get-outcome.ts
  packages/ethersjs-provider/src/EthersProvider.ts
Labels: project/sportsbook

#8046 convert modal containers
  packages/augur-ui/src/modules/app/components/app.tsx
  packages/augur-ui/src/modules/modal/components/modal-disclaimer.tsx
  packages/augur-ui/src/modules/modal/components/modal-network-connect.tsx
  packages/augur-ui/src/modules/modal/components/modal-network-disconnected.tsx
  packages/augur-ui/src/modules/modal/components/modal-view.tsx
  packages/augur-ui/src/modules/modal/containers/modal-disclaimer.ts
  packages/augur-ui/src/modules/modal/containers/modal-loading.ts
  packages/augur-ui/src/modules/modal/containers/modal-migrate-rep.ts
  packages/augur-ui/src/modules/modal/containers/modal-network-connect.ts
  packages/augur-ui/src/modules/modal/containers/modal-network-disconnected.ts
  packages/augur-ui/src/modules/modal/containers/modal-view.ts
  packages/augur-ui/src/modules/modal/loading.tsx
  packages/augur-ui/src/modules/modal/migrate-rep.tsx
Labels: project/sportsbook

#8048 fix pagination on market list
  packages/augur-ui/src/modules/markets-list/components/markets-view.tsx
Labels: project/sportsbook

#8037 Betting ui onboarding fixes
  packages/augur-ui/src/modules/app/components/top-nav/top-nav.tsx
  packages/augur-ui/src/modules/auth/actions/update-sdk.ts
  packages/augur-ui/src/modules/modal/components/modal-view.tsx
  packages/augur-ui/src/modules/modal/containers/modal-account-created.ts
  packages/augur-ui/src/modules/modal/containers/modal-augur-uses-dai.ts
  packages/augur-ui/src/modules/modal/containers/modal-buy-dai.ts
  packages/augur-ui/src/modules/modal/containers/modal-p2p-trading.ts
  packages/augur-ui/src/modules/modal/containers/modal-signin.ts
  packages/augur-ui/src/modules/modal/containers/modal-test-bet.ts
  packages/augur-ui/src/modules/modal/loading.tsx
  packages/augur-ui/src/modules/modal/modal.styles.less
Labels: project/sportsbook

#8051 convert modals
  packages/augur-ui/src/modules/auth/actions/load-account-data-from-local-storage.ts
  packages/augur-ui/src/modules/auth/connect-dropdown.tsx
  packages/augur-ui/src/modules/modal/common.tsx
  packages/augur-ui/src/modules/modal/components/modal-migrate-market.tsx
  packages/augur-ui/src/modules/modal/components/modal-participate.tsx
  packages/augur-ui/src/modules/modal/components/modal-universe-selector.tsx
  packages/augur-ui/src/modules/modal/components/modal-view.tsx
  packages/augur-ui/src/modules/modal/containers/modal-migrate-market.ts
  packages/augur-ui/src/modules/modal/containers/modal-participate.ts
  packages/augur-ui/src/modules/modal/containers/modal-reporting.ts
  packages/augur-ui/src/modules/modal/containers/modal-transactions.ts
  packages/augur-ui/src/modules/modal/containers/modal-transfer.ts
  packages/augur-ui/src/modules/modal/containers/modal-universe-selector.ts
  packages/augur-ui/src/modules/modal/containers/transfer-my-dai.ts
  packages/augur-ui/src/modules/modal/message.tsx
  packages/augur-ui/src/modules/modal/modal.styles.less
  packages/augur-ui/src/modules/modal/onboarding.tsx
  packages/augur-ui/src/modules/modal/reporting.tsx
  packages/augur-ui/src/modules/modal/transactions.tsx
  packages/augur-ui/src/modules/modal/transfer-form.tsx
  packages/augur-ui/src/modules/orders/actions/liquidity-management.ts
  packages/augur-ui/src/modules/orders/actions/pending-orders-management.ts
Labels: project/sportsbook

#8052 convert sign up modal
  packages/augur-ui/src/modules/auth/actions/login-with-fortmatic.ts
  packages/augur-ui/src/modules/auth/actions/login-with-injected-web3.ts
  packages/augur-ui/src/modules/auth/actions/login-with-portis.ts
  packages/augur-ui/src/modules/auth/actions/login-with-torus.ts
  packages/augur-ui/src/modules/auth/actions/update-sdk.ts
  packages/augur-ui/src/modules/modal/components/modal-view.tsx
  packages/augur-ui/src/modules/modal/containers/modal-signin.ts
  packages/augur-ui/src/modules/modal/signin.tsx
Labels: project/sportsbook

#8062 convert onboarding modals
  packages/augur-ui/src/modules/market/components/market-header/market-header-reporting.tsx
  packages/augur-ui/src/modules/modal/components/modal-view.tsx
  packages/augur-ui/src/modules/modal/containers/modal-account-created.ts
  packages/augur-ui/src/modules/modal/containers/modal-augur-uses-dai.ts
  packages/augur-ui/src/modules/modal/containers/modal-buy-dai.ts
  packages/augur-ui/src/modules/modal/containers/modal-p2p-trading.ts
  packages/augur-ui/src/modules/modal/containers/modal-test-bet.ts
  packages/augur-ui/src/modules/modal/containers/modal-tutorial-intro.ts
  packages/augur-ui/src/modules/modal/containers/modal-tutorial-outro.ts
  packages/augur-ui/src/modules/modal/onboarding-modals.tsx
Labels: project/sportsbook

#8079 rid of shared containers
  packages/augur-ui/src/modules/app/store/pending-orders.tsx
  packages/augur-ui/src/modules/modal/components/modal-view.tsx
  packages/augur-ui/src/modules/modal/containers/modal-claim-fees.ts
  packages/augur-ui/src/modules/modal/containers/modal-claim-markets-proceeds.ts
  packages/augur-ui/src/modules/modal/containers/modal-open-orders.ts
  packages/augur-ui/src/modules/modal/containers/modal-unsigned-orders.ts
  packages/augur-ui/src/modules/modal/shared-modals.tsx
Labels: project/sportsbook

#8084 convert msg modals
  packages/augur-ui/src/modules/account/actions/get-dai.ts
  packages/augur-ui/src/modules/account/actions/get-rep.ts
  packages/augur-ui/src/modules/modal/components/modal-view.tsx
  packages/augur-ui/src/modules/modal/containers/modal-create-market.ts
  packages/augur-ui/src/modules/modal/containers/modal-creation-help.ts
  packages/augur-ui/src/modules/modal/containers/modal-dai-faucet.ts
  packages/augur-ui/src/modules/modal/containers/modal-discard.ts
  packages/augur-ui/src/modules/modal/containers/modal-dr-quick-guide.ts
  packages/augur-ui/src/modules/modal/containers/modal-finalize.ts
  packages/augur-ui/src/modules/modal/containers/modal-help.ts
  packages/augur-ui/src/modules/modal/containers/modal-initialize-account.ts
  packages/augur-ui/src/modules/modal/containers/modal-invalid-market-rules.ts
  packages/augur-ui/src/modules/modal/containers/modal-market-loading.ts
  packages/augur-ui/src/modules/modal/containers/modal-migrate-market.ts
  packages/augur-ui/src/modules/modal/containers/modal-mismatch.ts
  packages/augur-ui/src/modules/modal/containers/modal-network-disabled.ts
  packages/augur-ui/src/modules/modal/containers/modal-odds.ts
  packages/augur-ui/src/modules/modal/containers/modal-rep-faucet.ts
  packages/augur-ui/src/modules/modal/containers/modal-sign-transaction.ts
  packages/augur-ui/src/modules/modal/containers/modal-wallet-error.ts
  packages/augur-ui/src/modules/modal/message-modals.tsx
Labels: project/sportsbook

#8113 move 3 box to app status
  packages/augur-ui/src/modules/app/store/app-status-hooks.ts
  packages/augur-ui/src/modules/app/store/constants.ts
  packages/augur-ui/src/modules/global-chat/actions/initialize-3box.ts
  packages/augur-ui/src/modules/global-chat/containers/global-chat.ts
  packages/augur-ui/src/modules/global-chat/reducers/initialized-3box.ts
  packages/augur-ui/src/modules/market/containers/market-comments.ts
  packages/augur-ui/src/modules/modal/containers/modal-global-chat.ts
  packages/augur-ui/src/reducers/index.ts
Labels: project/sportsbook

#8115 fixed a typo in odds-menu imports
  packages/augur-ui/src/modules/app/components/odds-menu.tsx
Labels: project/sportsbook

#8119 empty-reducer-error-fix
  packages/augur-artifacts/src/environments/demo.json
  packages/augur-ui/src/appStore/index.ts
  packages/orbit-web/dist/index.html
Labels: project/sportsbook

#8121 Fix broken reference to formatEthereumAddress
  packages/augur-ui/src/modules/auth/actions/transfer-funds.ts
Labels: release/v2.0

#8122 rm containers from chat and some dispatches
  packages/augur-ui/src/modules/account/actions/get-rep.ts
  packages/augur-ui/src/modules/app/actions/init-augur.ts
  packages/augur-ui/src/modules/app/components/top-nav/top-nav.tsx
  packages/augur-ui/src/modules/auth/actions/login-with-fortmatic.ts
  packages/augur-ui/src/modules/auth/actions/login-with-injected-web3.ts
  packages/augur-ui/src/modules/auth/actions/login-with-portis.ts
  packages/augur-ui/src/modules/auth/actions/login-with-torus.ts
  packages/augur-ui/src/modules/events/actions/liquidity-transactions.ts
  packages/augur-ui/src/modules/events/actions/log-handlers.ts
  packages/augur-ui/src/modules/global-chat/components/global-chat.tsx
  packages/augur-ui/src/modules/global-chat/containers/global-chat.ts
  packages/augur-ui/src/modules/market/components/common/comments/facebook-comments.tsx
  packages/augur-ui/src/modules/market/components/common/comments/market-comments.tsx
  packages/augur-ui/src/modules/market/components/market-orders-positions-table/market-orders-positions-table.tsx
  packages/augur-ui/src/modules/market/components/market-view/market-view.tsx
  packages/augur-ui/src/modules/market/containers/market-comments.ts
  packages/augur-ui/src/modules/modal/components/modal-global-chat.tsx
  packages/augur-ui/src/modules/modal/components/modal-view.tsx
  packages/augur-ui/src/modules/modal/containers/modal-global-chat.ts
  packages/augur-ui/src/modules/orders/selectors/user-open-orders.ts
  packages/augur-ui/src/modules/routes/components/routes/routes.tsx
  packages/augur-ui/src/services/analytics/with-page-analytic.tsx
Labels: project/sportsbook

#8136 remove-dispatch
  packages/augur-ui/src/modules/app/actions/init-augur.ts
  packages/augur-ui/src/modules/app/containers/app.ts
  packages/augur-ui/src/modules/events/actions/listen-to-updates.ts
  packages/augur-ui/src/modules/events/actions/log-handlers.ts
  packages/augur-ui/src/modules/events/actions/wrap-log-handler.ts
  packages/augur-ui/src/modules/forking/actions/migrate-through-one-fork.ts
  packages/augur-ui/src/modules/markets-list/actions/update-login-account-settings.ts
  packages/augur-ui/src/modules/markets/actions/load-create-market-history.ts
  packages/augur-ui/src/modules/markets/actions/market-creator-fees-management.ts
  packages/augur-ui/src/modules/markets/actions/submit-new-market.ts
  packages/augur-ui/src/modules/orders/actions/liquidity-management.ts
  packages/augur-ui/src/modules/orders/actions/pending-orders-management.ts
  packages/augur-ui/src/modules/routes/components/routes/routes.tsx
  packages/augur-ui/src/modules/universe/actions/sync-universe.ts
  packages/augur-ui/src/services/augursdk.ts
Labels: project/sportsbook

#8140 remove containers
  packages/augur-ui/src/main.tsx
  packages/augur-ui/src/modules/app/components/app.tsx
  packages/augur-ui/src/modules/app/containers/app.ts
  packages/augur-ui/src/modules/app/hocs/rewrite-url-params/index.tsx
  packages/augur-ui/src/modules/common/buttons.tsx
  packages/augur-ui/src/modules/common/labels.tsx
Labels: project/sportsbook

#8143 Rm containers 2
  packages/augur-ui/src/appStore/index.ts
  packages/augur-ui/src/main.tsx
  packages/augur-ui/src/modules/auth/actions/load-account-data-from-local-storage.ts
  packages/augur-ui/src/modules/common/buttons.tsx
  packages/augur-ui/src/modules/common/labels.tsx
  packages/augur-ui/src/modules/global-chat/actions/initialize-3box.ts
  packages/augur-ui/src/modules/market/components/market-orders-positions-table/market-orders-positions-table.tsx
  packages/augur-ui/src/modules/markets/actions/load-markets-info.ts
  packages/augur-ui/src/modules/markets/actions/load-markets.ts
  packages/augur-ui/src/modules/markets/actions/update-new-market.ts
  packages/augur-ui/src/modules/markets/selectors/market.ts
  packages/augur-ui/src/modules/orders/selectors/user-open-orders.ts
  packages/augur-ui/src/modules/positions/selectors/login-account-positions.ts
  packages/augur-ui/src/modules/reporting/common.tsx
  packages/augur-ui/src/modules/routes/components/routes/routes.tsx
  packages/augur-ui/src/modules/types.ts
  packages/augur-ui/src/modules/universe-cards/actions/switch-universe.ts
  packages/augur-ui/src/reducers/index.ts
Labels: project/sportsbook

#8149 get-markets-updates
  packages/augur-sdk/src/state/getter/Markets.ts
Labels: project/sportsbook

#8144 update packages
  packages/augur-ui/config/webpack.common.config.js
  packages/augur-ui/package.json
  yarn.lock
Labels: project/sportsbook

#8178 Sportsbook markets
  packages/augur-ui/src/modules/app/components/inner-nav/markets-list-filters.styles.less
  packages/augur-ui/src/modules/app/store/constants.ts
  packages/augur-ui/src/modules/common/constants.ts
  packages/augur-ui/src/modules/common/labels.styles.less
  packages/augur-ui/src/modules/create-market/components/review.tsx
  packages/augur-ui/src/modules/events/actions/log-handlers.ts
  packages/augur-ui/src/modules/filter-sort/filter-search.tsx
  packages/augur-ui/src/modules/market-cards/common.styles.less
  packages/augur-ui/src/modules/market-cards/common.tsx
  packages/augur-ui/src/modules/market-cards/market-card.tsx
  packages/augur-ui/src/modules/market-cards/sports-market-card.styles.less
  packages/augur-ui/src/modules/market-cards/sports-market-card.tsx
  packages/augur-ui/src/modules/market/components/common/common.tsx
  packages/augur-ui/src/modules/market/components/common/market-title.tsx
  packages/augur-ui/src/modules/markets-list/components/landing-hero.tsx
  packages/augur-ui/src/modules/markets-list/components/markets-header.tsx
  packages/augur-ui/src/modules/markets-list/components/markets-landing-page.tsx
  packages/augur-ui/src/modules/markets-list/components/markets-list.tsx
  packages/augur-ui/src/modules/markets-list/components/markets-view.styles.less
  packages/augur-ui/src/modules/markets-list/components/markets-view.tsx
  packages/augur-ui/src/modules/markets/actions/load-markets.ts
  packages/augur-ui/src/modules/markets/store/markets-hooks.ts
  packages/augur-ui/src/modules/trading/store/betslip-hooks.ts
Labels: project/sportsbook

#8180 add betslip to window and as app constant
  packages/augur-ui/src/modules/trading/store/betslip-hooks.ts
  packages/augur-ui/src/modules/trading/store/betslip.tsx
Labels: project/sportsbook

#8191 Optimize OrderEvent/BulkOrderEvent on initial sync
  packages/augur-sdk/src/state/db/ZeroXOrders.ts
Labels: release/v2.0, type/optimization

#8204 Send bets - add place trade, add outcome id and price to add bets
  packages/augur-ui/src/modules/market-cards/common.tsx
  packages/augur-ui/src/modules/trading/store/betslip-hooks.ts
  packages/augur-ui/src/modules/trading/store/constants.ts
Labels: project/sportsbook

#8221 Master merge 6 29 2020
  packages/augur-artifacts/src/environments/default.json
  packages/augur-artifacts/src/environments/demo.json
  packages/augur-artifacts/src/environments/kovan.json
  packages/augur-artifacts/src/environments/matic.json
  packages/augur-core/src/libraries/DeploymentVerifier.ts
  packages/augur-core/tsconfig.json
  packages/augur-sdk-lite/src/AugurLite.ts
  packages/augur-sdk-lite/src/utils/hotloadKovanTest.ts
  packages/augur-sdk/src/Augur.ts
  packages/augur-sdk/src/state/create-api.ts
  packages/augur-sdk/src/state/db/MarketDB.ts
  packages/augur-sdk/src/state/sync/BlockAndLogStreamerSyncStrategy.ts
  packages/augur-templates/src/templates.ts
  packages/augur-tools/src/flash/scripts.ts
  packages/augur-tools/src/templates-source.ts
  packages/augur-tools/src/templates-template.ts
  packages/augur-ui/src/modules/app/actions/init-augur.ts
  packages/augur-ui/src/modules/app/components/app.tsx
  packages/augur-ui/src/modules/app/components/side-nav/side-nav.tsx
  packages/augur-ui/src/modules/app/components/top-nav/top-nav.tsx
  packages/augur-ui/src/modules/auth/actions/login-with-torus.ts
  packages/augur-ui/src/modules/common/form.tsx
  packages/augur-ui/src/modules/common/labels.styles.less
  packages/augur-ui/src/modules/common/labels.tsx
  packages/augur-ui/src/modules/contracts/actions/contractCalls.ts
  packages/augur-ui/src/modules/create-market/components/common.tsx
  packages/augur-ui/src/modules/create-market/components/form-details.tsx
  packages/augur-ui/src/modules/events/actions/log-handlers.ts
  packages/augur-ui/src/modules/market/components/market-view/market-view.tsx
  packages/augur-ui/src/modules/markets/actions/load-markets.ts
  packages/augur-ui/src/modules/modal/common.tsx
  packages/augur-ui/src/modules/modal/components/modal-frozen-funds.tsx
  packages/augur-ui/src/modules/modal/migrate-rep.tsx
  packages/augur-ui/src/modules/modal/modal.styles.less
  packages/augur-ui/src/services/augursdk.ts
  packages/augur-ui/src/services/augursdklite.ts
  packages/augur-ui/src/utils/debounce.ts
  packages/augur-utils/src/configuration.ts
Labels: project/sportsbook

#8228 Some adjustments
  packages/augur-ui/src/modules/market/components/market-view/market-view.tsx
  packages/augur-ui/src/modules/markets/actions/load-markets.ts
  packages/augur-ui/src/modules/trading/components/wrapper.tsx
Labels: project/sportsbook

#8237 Fix orders and positions, fills
  packages/augur-ui/src/modules/app/store/app-status-hooks.ts
  packages/augur-ui/src/modules/market/components/market-orders-positions-table/market-orders-positions-table.tsx
  packages/augur-ui/src/modules/notifications/selectors/notification-state.ts
  packages/augur-ui/src/modules/orders/selectors/filled-orders.ts
  packages/augur-ui/src/modules/orders/selectors/user-open-orders.ts
  packages/augur-ui/src/modules/portfolio/components/common/market-row.tsx
  packages/augur-ui/src/modules/portfolio/components/orders/open-orders.tsx
  packages/augur-ui/src/modules/portfolio/selectors/select-markets-filled-orders.ts
  packages/augur-ui/src/modules/trading/common.tsx
Labels: project/sportsbook

#8249 Marketcard updates
  packages/augur-ui/src/modules/events/actions/log-handlers.ts
  packages/augur-ui/src/modules/market-cards/common.styles.less
  packages/augur-ui/src/modules/market-cards/common.tsx
  packages/augur-ui/src/modules/market-cards/sports-market-card.styles.less
  packages/augur-ui/src/modules/market-cards/sports-market-card.tsx
  packages/augur-ui/src/modules/trading/store/betslip-hooks.ts
Labels: project/sportsbook
